#!/bin/bash --login
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=16
#PBS -N Diversity_CheeseData
#PBS -A d411-training
#PBS -j oe

echo "setting temporary directory"
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

echo "loading virtual environment"
conda deactivate
conda activate qiime1

echo "creating and cd to output directory"
mkdir -p ~/output/owndataDiversity/
cd ~/output/owndataDiversity/


echo "Calculating Joined Diversity..."

core_diversity_analyses.py \
-i ~/output/OTUf/readjoin/otu_table.biom \
-m ~/Map.tsv \
-t ~/output/OTUf/readjoin/97_otus.tree \
-o ./Dataf \
-e 34000 \
-a -O 16 \
--recover_from_failure

echo "Calculation Complete"

echo "closing environment"
conda deactivate

### end script
