#!/bin/bash --login
#PBS -l walltime=2:00:00
#PBS -l select=1:ncpus=16
#PBS -N yeet
#PBS -A d411-training
#PBS -j oe

echo "setting temporary directory"
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

echo "loading virtual environment"
conda deactivate
conda activate qiime1

echo "creating and cd to output directory"
mkdir -p ~/output/taxaf/
cd ~/output/taxaf/


summarize_taxa.py \
-i ~/output/OTUf/readjoin/otu_table.biom \
-u 0.02

echo "Calculation Complete"

echo "closing environment"
conda deactivate

### end script


