#!/bin/bash --login
#PBS -l walltime=06:00:00
#PBS -l select=1:ncpus=16
#PBS -N otu_CheeseData
#PBS -A d411-training
#PBS -j oe

echo "setting temporary directory"
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

echo "loading virtual environment"
conda deactivate
conda activate qiime1

echo "creating and cd to output directory"
mkdir -p ~/output/OTUf/
cd ~/output/OTUf/


echo "Read Join Running..."
for i in {1..3}
do
    echo "run $i"
    time pick_closed_reference_otus.py \
    -i ~/output/readjoinf/readjoin/seqs.fna \
    -o readjoin \
    -f -a -O 16
done
echo "Read Join Complete"



echo "closing environment"
conda deactivate

### end script
