#!/bin/bash --login
#PBS -l walltime=2:00:00
#PBS -l select=1:ncpus=16
#PBS -N Permanova
#PBS -A d411-training
#PBS -j oe

echo "setting temporary directory"
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

echo "loading virtual environment"
conda deactivate
conda activate qiime1

echo "creating and cd to output directory"
mkdir -p ~/output/permanovaf/
cd ~/output/permanovaf/


echo "Calculating Joined Diversity..."

compare_categories.py --method permanova \
-i ~/output/owndataDiversity/Dataf/bdiv_even34000/unweighted_unifrac_dm.txt \
-m ~/Brie.tsv \
-c Store_Type \
-o ~/output/Brie/store \
-n 999 \

echo "Calculation Complete"

echo "closing environment"
conda deactivate

### end script:

