#!/bin/bash --login
#PBS -l walltime=2:00:00
#PBS -l select=1:ncpus=16
#PBS -N Upgma
#PBS -A d411-training
#PBS -j oe

echo "setting temporary directory"
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

echo "loading virtual environment"
conda deactivate
conda activate qiime1

echo "creating and cd to output directory"
mkdir -p ~/output/upgmaf/
cd ~/output/upgmaf/

upgma_cluster.py \
-i ~/output/owndataDiversity/Dataf/bdiv_even34000/unweighted_unifrac_dm.txt \
-o upgmaf \

echo "Calculation Complete"

echo "closing environment"
conda deactivate
